### ISSUE TITLE
Rename Genes Clarification 

### ISSUE THREAD

**Issue by Oscar-Wu-UTSW** [vertesy/Seurat.Pipeline#6]
For the RenameGenes function in Seurat utils, how exactly does one manipulate the code to replace the dimnames with a new set of genes? I have a csv file containing the new names for all 28,444 genes in the original Seurat object, and would like to replace them with those names. In other words, what exactly does one change for "ls.Seurat" and "HGNC.updated.genes$Suggested.Symbol"? Thanks so much!

```r
RenameGenesSeurat <- function(obj = ls.Seurat[[i]], newnames = HGNC.updated[[i]]$Suggested.Symbol) { # Replace gene names in different slots of a Seurat object. Run this before integration. Run this before integration. It only changes obj@assays$RNA@counts, @DaTa and @scale.data.
print("Run this before integration. It only changes obj@assays$RNA@counts, @DaTa and @scale.data.")
RNA <- obj@assays$RNA

if (nrow(RNA) == length(newnames)) {
if (length(RNA@counts)) RNA@counts@Dimnames[[1]] <- newnames
if (length(RNA@data)) RNA@data@Dimnames[[1]] <- newnames
if (length(RNA@scale.data)) RNA@scale.data@Dimnames[[1]] <- newnames
} else {"Unequal gene sets: nrow(RNA) != nrow(newnames)"}
obj@assays$RNA <- RNA
return(obj)
}
##RenameGenesSeurat(obj = SeuratObj, newnames = HGNC.updated.genes$Suggested.Symbol)
```

**Comment by vertesy** [comment]
Hey Oscar, 

You can just provide:
 
1.  `obj = `your seurat object
2. `newnames = ` a vector of your symbols. Read it in from your file with `read.csv`.

These are just defaults made to use with another function in the package:
>  "ls.Seurat" and "HGNC.updated.genes$Suggested.Symbol" 

```r
RenamedObject <- RenameGenesSeurat(obj = YourObject , newnames =  YourNames)
```
