### ISSUE TITLE
Missing iteration index

### ISSUE THREAD

**Issue by jn-goe** [vertesy/Seurat.Pipeline#7]
Iteration index `i` missing in `add.meta.fraction(..., obj = ls.Seurat[[1]])`.

https://github.com/vertesy/Seurat.Pipeline/blob/9b33ec40b7862df6fa36f27f6118055e44aa2f20/00.Example.pipeline.for.sc.analysis.LOCAL.R#L49

https://github.com/vertesy/Seurat.Pipeline/blob/9b33ec40b7862df6fa36f27f6118055e44aa2f20/00.Example.pipeline.for.sc.analysis.LOCAL.R#L50

**Comment by vertesy** [comment]
Thanks Julia! fixed now
